create table public."Funcionarios" (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  nome text null,
  email text null,
  senha text null,
  role text null default 'funcionario'::text,
  constraint Funcionarios_pkey primary key (id)
) TABLESPACE pg_default;