create table public."reportUsers" (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  nome character varying not null,
  email character varying not null,
  rua character varying not null,
  bairro character varying not null,
  descricao text null,
  tipo_problema public.tipo_problema null,
  status public.status_reporte null default 'recebido'::status_reporte,
  resposta_admin text null,
  respondido_em timestamp without time zone null,
  constraint reportUsers_pkey primary key (id)
) TABLESPACE pg_default;