create table public."Users" (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  nome_completo character varying not null,
  email character varying not null,
  senha character varying not null,
  data_nascimento date not null,
  telefone character varying not null,
  cidade character varying not null,
  estado character varying not null,
  pais character varying not null,
  bairro character varying not null,
  "resetToken" text null,
  "tokenExpiration" text null,
  role character varying null default 'users'::character varying,
  constraint Users_pkey primary key (id)
) TABLESPACE pg_default;